name: uione
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1
environment:
  sdk: ^3.8.0

# _________________________________________________________________________________________________________________________

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3   
  intl: ^0.20.2               # Internationalization & Localization
  get_storage: ^2.1.1
  # get_it: ^8.0.3            # DependencyInjection(DI)     --replace by Riverpod
  # get: ^4.7.2               # state & DI & Routing        --replace by Riverpod
  riverpod: ^3.0.0            # state & DI----Testable
  rxdart: ^0.28.0             # Streams manipulation 
  go_router: ^16.2.4          # routing
  # permission_handler: ^12.0.1
  # -------------------------------------------------------------
  # dio: ^5.8.0+1
  # url_launcher: ^6.3.1
  # webview_flutter: ^4.13.0
  # -------------------------------------------------------------
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  # open_file: ^3.5.10
  # path_provider: ^2.1.5
  # downloads_path_provider_28: ^0.1.2
  # flutter_downloader: ^1.12.0
  # share_plus: ^11.1.0

  # -------------UI----------------------------------------------
  # auto_animated: ^3.2.0
  # lottie: ^3.3.1
  # dotlottie_loader: ^0.0.5
  hexagon: ^0.2.0
# ____________________________________________________________________________________________________________________
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner: 
# _____________________flutter_gen_______________________________________________________________________________
flutter_gen:
  # parse_metadata: true # <- Build Time: Add this line (default: false)
  output: lib/gen/
  line_length: 120
  # Optional
  # integrations:
  #   image: true
  #   flutter_svg: true
  #   rive: true
  #   lottie: true
  colors:
    inputs:
      - assets/colors/colors.xml
    outputs:
      class_name: AppColors


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
  fonts:
  - family: Gilroy
    fonts:
      - asset: assets/fonts/Gilroy-Regular.ttf

  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-SemiBold.ttf

# ____________________flutter_gen_________________________________________________________________________________
